apiVersion: apps/v1
kind: Deployment
metadata:
  name: useradd
  namespace: teste
  labels:
    app: useradd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: useradd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: useradd
    spec:
      containers:
      - image: ailtonmsj/useradd-jvm:1.0.0
        name: useradd-jvm
        imagePullPolicy: Always
        resources: {}
        env:
        - name: QUEUE_URL
          value:
        - name: AWS_ACCESS_KEY_ID
          value:
        - name: AWS_SECRET_ACCESS_KEY
          value:
        - name:
          value:
